### ISSUE TITLE
"/bin/sh: perl6: not found" after update 8 may

### ISSUE THREAD

**Issue by atroxaper** [JJ/docker-raku-test#1]
Travis builds are failed after container update from 8 may.
It says `/bin/sh: perl6: not found`

**IMAGE ID**: `0cd12d4e2d90`

For example https://travis-ci.org/atroxaper/p6-Scheduler-DelayBetween/builds/529875340

**Comment by JJ** [comment]
Ah, OK, good one. Thanks for reporting. I'll try to have it fixed now. Sorry.
