### ISSUE TITLE
XML::Writer failing on Travis

### ISSUE THREAD

**Issue by librasteve** [JJ/docker-raku-test#12]
Hi @JJ --- I am getting a fail on a dependency load of XML::Writer for my [Physics::Constants](https://github.com/p6steve/raku-Physics-Constants) module on [Travis](https://app.travis-ci.com/github/p6steve/raku-Physics-Constants), please can you help?

All works fine on my local machine with both the Math::Constants zef release and a git clone just now of with the recent PR.

Local kit is macOS Big Sur on M1...
Welcome to Rakudo(tm) v2021.04.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2021.04.

Here is the build log (fails at line 154):

Build system information
105
1060.02s0.00s0.01s0.27s0.00s0.00s0.00s0.01s0.00s0.09s0.00s0.01s0.00s0.00s6.03s0.00s2.65s0.00s2.51s
docker_mtu_and_registry_mirrors
resolvconf
services
1073.01s$ sudo systemctl start docker
git.checkout
1080.51s$ git clone --depth=50 --branch=master https://github.com/p6steve/raku-Physics-Constants.git p6steve/raku-Physics-Constants
118
1190.01s$ bash -c 'echo $BASH_VERSION'
1204.3.48(1)-release
121
install.1
1226.17s$ docker pull jjmerelo/raku-test
install.2
1270.06s$ docker images
13024.91s$ travis_wait docker run -t -v  $TRAVIS_BUILD_DIR:/test jjmerelo/raku-test
131
132
133
138The command docker run -t -v /home/travis/build/p6steve/raku-Physics-Constants:/test jjmerelo/raku-test exited with 1.
139
140Log:
141
142===> Searching for missing dependencies: Math::Constants, Physics::Measure
143===> Updating fez mirror: http://360.zef.pm/
144===> Updated fez mirror: http://360.zef.pm/
145===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
146===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
147===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
148===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
149===> Searching for missing dependencies: SVG, SVG::Plot, Math::Polygons, Physics::Unit, Test::META
150===> Searching for missing dependencies: META6:ver<0.0.24+>, URI, License::SPDX, XML::Writer
151===> Searching for missing dependencies: JSON::Class:ver<0.0.14+>, JSON::Class:ver<0.0.15+>, JSON::Name, JSON::Fast
152===> Searching for missing dependencies: JSON::Marshal:ver<0.0.21+>, JSON::Unmarshal:ver<0.08+>
153===> Testing: XML::Writer
154===> Testing [FAIL]: XML::Writer
155Aborting due to test failure: XML::Writer (use --force-test to override)
156===> Testing: Physics::Constants:ver<1.0.0>:auth<github:p6steve>:api<1>
157===> Testing [FAIL]: Physics::Constants:ver<1.0.0>:auth<github:p6steve>:api<1>
158Aborting due to test failure: Physics::Constants:ver<1.0.0>:auth<github:p6steve>:api<1> (use --force-test to override)
159/home/travis/.travis/functions: line 607:  3305 Terminated              travis_jigger "${!}" "${timeout}" "${cmd[@]}"
134The command "travis_wait docker run -t -v  $TRAVIS_BUILD_DIR:/test jjmerelo/raku-test" exited with 1.
135
136
137Done. Your build exited with 1.

**Comment by JJ** [comment]
Thanks for the report, I'll check it out. Off the top of my head, it might be due to some non-Raku dependence missing. But I'll take a look.

**Comment by JJ** [comment]
It might be a temporal travis failure, since that's where the error is happening. I'm forking your repo and trying to reproduce it anyway.

**Comment by JJ** [comment]
Well, I don't have any Travis credits....

**Comment by JJ** [comment]
I have managed to reproduce the error locally. I would say it's a JSON::Fast error:

```
docker run -t -v  `pwd`:/test jjmerelo/raku-test    
===> Searching for missing dependencies: Math::Constants, Physics::Measure
===> Updating fez mirror: http://360.zef.pm/
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated fez mirror: http://360.zef.pm/
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Searching for missing dependencies: Test::META, SVG, SVG::Plot, Math::Polygons, Physics::Unit
===> Searching for missing dependencies: XML::Writer, META6:ver<0.0.24+>, URI, License::SPDX
===> Searching for missing dependencies: JSON::Class:ver<0.0.15+>, JSON::Name, JSON::Fast, JSON::Class:ver<0.0.14+>
===> Searching for missing dependencies: JSON::Marshal:ver<0.0.21+>, JSON::Unmarshal:ver<0.08+>
===> Testing: JSON::Fast:ver<0.16>
===> Testing [FAIL]: JSON::Fast:ver<0.16>
Aborting due to test failure: JSON::Fast:ver<0.16> (use --force-test to override)
===> Testing: Physics::Constants:ver<1.0.0>:auth<github:p6steve>:api<1>
===> Testing [FAIL]: Physics::Constants:ver<1.0.0>:auth<github:p6steve>:api<1>
Aborting due to test failure: Physics::Constants:ver<1.0.0>:auth<github:p6steve>:api<1> (use --force-test to override)
```

**Comment by JJ** [comment]
This is resulting in a massive yak-shaving session. My money is now on something having changed in the zef-prove6 interface. This is definitely a reason to eliminate that from my containers, but I need to see why that happens specifically for this distribution.

**Comment by JJ** [comment]
Well, finally I think I found the issue: it was fixed here https://github.com/ugexe/zef/commit/4319221998d203c0908140e524ac782c553f22c4 apparently. I'll upgrade zef and see if this fixes the stuff.

**Comment by librasteve** [comment]
This issue is resolved - there is a new kind of failure on Physics::Constants... but this one is for me to fix!

===> Testing: Physics::Constants:ver<1.0.0>:auth<github:p6steve>:api<1>
165# Failed test '~kg-amu (Na)'
166# at t/01-tst.t line 25
167# expected: '6.02214076e+23 mol^-1'
168#      got: '6.0221407599999996e+26 mol^-1'
169# You failed 1 test of 10
