### ISSUE TITLE
"zef: command not found"

### ISSUE THREAD

**Issue by moretrim** [JJ/docker-raku-test#2]
My test environments haven’t been able to find the `zef` executable (if there is one around) ever since some time around 4 December. My docker-fu is near nonexistent so I'm not too sure how to diagnose the situation.

According to the logs image ID is `14810323e0df`, and while it looks like there was [a rebuild this week](https://hub.docker.com/r/jjmerelo/test-perl6/builds) it points to the same source as before.

**Comment by JJ** [comment]
Totally my fault. Let me fix it.
