### ISSUE TITLE
Force zef --verbose install ?

### ISSUE THREAD

**Issue by librasteve** [JJ/docker-raku-test#7]
Great module - really helpful!!

My module takes about 12 mins to build (yes really!) --- until we have AST I am creating about 600 objects --- normally this is not too bad as I propose zef --verbose install xxx . How can I force verbose in travis-ci to prevent timeout?

3.01s$ sudo systemctl start docker
git.checkout
108$ git clone --depth=50 --branch=master https://github.com/p6steve/raku-Physics-Measure.git p6steve/raku-Physics-Measure
116
1170.01s$ bash -c 'echo $BASH_VERSION'
1184.3.48(1)-release
119
install.1
1206.57s$ docker pull jjmerelo/raku-test
install.2
1270.06s$ docker images
130$ docker run -t -v  $TRAVIS_BUILD_DIR:/test jjmerelo/raku-test
131This is Rakudo version 2020.09 built on MoarVM version 2020.09
132implementing Raku 6.d.
133===> Searching for missing dependencies: SVG, SVG::Plot, Math::Polygons
134===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
135===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
136===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
137===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
138===> Searching for missing dependencies: XML::Writer
139===> Testing: XML::Writer
140===> Testing [OK] for XML::Writer
141===> Testing: SVG
142===> Testing [OK] for SVG
143===> Testing: SVG::Plot
144===> Testing [OK] for SVG::Plot
145===> Testing: Math::Polygons:ver<0.0.4>:auth<github:p6steve>:api<1>
146===> Testing [OK] for Math::Polygons:ver<0.0.4>:auth<github:p6steve>:api<1>
147===> Installing: XML::Writer
148===> Installing: SVG
149===> Installing: SVG::Plot
150===> Installing: Math::Polygons:ver<0.0.4>:auth<github:p6steve>:api<1>
151
1523 bin/ scripts [svg.html Polygons.p6 Tree.p6] installed to:
153/home/raku/.raku/share/perl6/site/bin
154===> Testing: Physics::Measure:ver<0.0.3>:auth<github:p6steve>:api<1>
155
156
157No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
158Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
159
160The build has been terminated

**Comment by JJ** [comment]
Theoretically, you should be able to pass flags directly to the test... But maybe it's not that easy. Let me think about it and I'll try to solve. Thanks for raising the issue anyway.
